# Generated by Django 3.0.8 on 2020-07-23 04:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('short', models.CharField(max_length=5, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MessagePopUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mesg_type', models.CharField(choices=[('A', 'All Pages'), ('H', 'Home Page')], max_length=1, unique=True)),
                ('mesg_html', models.TextField()),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='pinax_Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('history', models.IntegerField(default=15, help_text='visible history in minutes')),
            ],
        ),
        migrations.CreateModel(
            name='RepeaterSite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SiteOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('value', models.CharField(max_length=60)),
                ('javascript_visible', models.BooleanField(default=False)),
                ('template_visible', models.BooleanField(default=False)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(db_index=True, max_length=100, unique=True)),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('system_id', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TalkGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dec_id', models.IntegerField()),
                ('alpha_tag', models.CharField(max_length=30)),
                ('common_name', models.CharField(blank=True, max_length=10, null=True)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('slug', models.SlugField(null=True)),
                ('public', models.BooleanField(default=True)),
                ('comments', models.CharField(blank=True, max_length=100, null=True)),
                ('mode', models.CharField(choices=[('A', 'Analog'), ('D', 'Digital'), ('E', 'Encrypted')], default='D', help_text='mode used by trunk-recorder', max_length=1)),
                ('priority', models.IntegerField(default=3, help_text='record priority used by trunk-recorder')),
                ('last_transmission', models.DateTimeField()),
                ('recent_usage', models.IntegerField(default=0)),
                ('_home_site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='radio.RepeaterSite')),
                ('_service_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='radio.Service')),
                ('play_source', models.ForeignKey(blank=True, help_text='default record source for playback', null=True, on_delete=django.db.models.deletion.CASCADE, to='radio.Source')),
                ('system', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='radio.System')),
            ],
            options={
                'ordering': ['alpha_tag'],
                'unique_together': {('dec_id', 'system')},
            },
        ),
        migrations.CreateModel(
            name='TalkGroupAccess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('default_group', models.BooleanField(default=False, help_text='new users get this group by default')),
                ('default_new_talkgroups', models.BooleanField(default=False, help_text='new talkgroups are added to this group')),
            ],
            options={
                'verbose_name_plural': 'talk group access',
            },
        ),
        migrations.CreateModel(
            name='TranmissionUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='WebHtml',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('bodytext', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dec_id', models.IntegerField()),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('type', models.CharField(choices=[('M', 'Mobile'), ('P', 'Portable'), ('B', 'Base'), ('D', 'Dispatch')], default='M', max_length=1)),
                ('number', models.IntegerField(default=1)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('agency', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='radio.Agency')),
                ('system', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='radio.System')),
            ],
            options={
                'unique_together': {('dec_id', 'system')},
            },
        ),
        migrations.CreateModel(
            name='Transmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('start_datetime', models.DateTimeField(db_index=True)),
                ('end_datetime', models.DateTimeField(blank=True, null=True)),
                ('audio_file', models.FileField(upload_to='')),
                ('audio_file_type', models.CharField(default='mp3', max_length=3, null=True)),
                ('audio_file_url_path', models.CharField(default='/', max_length=100)),
                ('talkgroup', models.IntegerField()),
                ('freq', models.IntegerField()),
                ('emergency', models.BooleanField(default=False)),
                ('play_length', models.FloatField(default=0.0)),
                ('from_default_source', models.BooleanField(default=True)),
                ('has_audio', models.BooleanField(default=True)),
                ('source', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='radio.Source')),
                ('system', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='radio.System')),
                ('talkgroup_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='radio.TalkGroup')),
                ('units', models.ManyToManyField(through='radio.TranmissionUnit', to='radio.Unit')),
            ],
            options={
                'ordering': ['-pk'],
                'permissions': (('download_audio', 'Can download audio clips'),),
            },
        ),
        migrations.AddField(
            model_name='tranmissionunit',
            name='transmission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='radio.Transmission'),
        ),
        migrations.AddField(
            model_name='tranmissionunit',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='radio.Unit'),
        ),
        migrations.CreateModel(
            name='StripePlanMatrix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=99)),
                ('radio_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='radio.Plan')),
                ('stripe_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='radio.pinax_Plan')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ScanList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=30, unique=True)),
                ('description', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('talkgroups', models.ManyToManyField(to='radio.TalkGroup')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='radio.Plan')),
                ('talkgroup_access', models.ManyToManyField(blank=True, to='radio.TalkGroupAccess')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MenuScanList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=1)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='radio.ScanList')),
            ],
            options={
                'ordering': ['order', 'name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('public', models.BooleanField(default=True)),
                ('transmissions', models.ManyToManyField(blank=True, to='radio.Transmission')),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('url', models.URLField(blank=True, max_length=400, null=True)),
                ('google_maps_url', models.URLField(blank=True, max_length=400, null=True)),
                ('visible', models.BooleanField(default=True)),
                ('ems_service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ems_service', to='radio.Agency')),
                ('fire_service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fire_service', to='radio.Agency')),
                ('police_service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='police_service', to='radio.Agency')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TalkGroupWithSystem',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('radio.talkgroup',),
        ),
        migrations.AddField(
            model_name='talkgroupaccess',
            name='talkgroups',
            field=models.ManyToManyField(to='radio.TalkGroupWithSystem'),
        ),
        migrations.CreateModel(
            name='MenuTalkGroupList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=1)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='radio.TalkGroupWithSystem')),
            ],
            options={
                'ordering': ['order', 'name'],
                'abstract': False,
            },
        ),
    ]
