# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-28 00:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TalkGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dec_id', models.IntegerField(unique=True)),
                ('alpha_tag', models.CharField(max_length=10)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_datetime', models.DateTimeField(db_index=True)),
                ('audio_file', models.FileField(upload_to='')),
                ('talkgroup', models.IntegerField()),
                ('freq', models.IntegerField()),
                ('emergency', models.BooleanField(default=False)),
                ('talkgroup_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='radio.TalkGroup')),
            ],
            options={
                'ordering': ['-start_datetime'],
            },
        ),
    ]
