# Generated by Django 3.0.8 on 2020-07-23 05:06

from django.db import migrations
from django.contrib.auth.models import User


def create_default_anonymous_user(apps, schema_editor):
    anon = User.objects.create_user('ANONYMOUS_USER', 'anonymous_user@example.com')
    # Make the user un usable
    anon.set_unusable_password()
    anon.is_active = False
    anon.save()

def create_default_plan(apps, schema_editor):
    plan = apps.get_model('radio', 'Plan')
    plan.objects.create(name='Default')

def create_default_agency(apps, schema_editor):
    agency = apps.get_model('radio', 'Agency')
    agency.objects.create(name='Default', short='_DEF_')

def create_default_system(apps, schema_editor):
    system = apps.get_model('radio', 'System')
    system.objects.create(name='Default')

def create_default_source(apps, schema_editor):
    source = apps.get_model('radio', 'Source')
    source.objects.create(description='Source')

def create_default_html(apps, schema_editor):
    index_html = """<h1>Welcome to Trunk-Player</h1>
<p>
  This is the new way to listen to public safety radio traffic. Many other sites allow you to live stream audio feeds from a radio scanner. This site is different from all the rest.
</p>
<p>
  We give you full control of which talkgroups/frequencies you want to hear. We also time shift (like a DVR) the transmissions. When two transmissions overlap using a standard scanner or streaming site you will only hear one, then you will scan into the second one in progresss, not here. The site will play the first transmission and when that is complete it will start to play the second transmission from the beginning, this is time shifting like a DVR.
</p>
<h2>
  Getting started
</h2>
<p>
  Jump right into the <a href="/scan/default/">Main Scan List</a>.
</p> """

    about_html = """<h2>About Trunk-Player</h2>
<p>This is the new way to listen to your local public safety radio system. Many other sites allow you to live stream audio feeds from a radio scanner. This site is different from all the rest.</p>
<p><strong>Features :</strong></p>
<ul>
  <li>You select the talk groups or scan lists you want to listen to</li>
  <li>History, you can listen to radio traffic from the past</li>
  <li>View which unit is transmitting</li>
  <li>Concurrent recording of multiple transmissions, you will not miss any of the action</li>
</ul> """

    WebHTML = apps.get_model('radio', 'WebHtml')
    index = WebHTML(name='index', bodytext=index_html).save()
    about = WebHTML(name='about', bodytext=about_html).save()

def create_default_email_option(apps, schema_editor):

    SiteOption = apps.get_model('radio', 'SiteOption')
    SiteOption(name='SEND_ADMIN_EMAIL_ON_NEW_USER',
               value = 'False',
               javascript_visible = False,
               template_visible = False,
               description = 'Send email to admin user when new user registers',
              ).save()

def create_default_copyright(apps, schema_editor):

    SiteOption = apps.get_model('radio', 'SiteOption')
    SiteOption(name='COPYRIGHT_NOTICE',
               value = 'Copyright 2020',
               javascript_visible = True,
               template_visible = True,
               description = 'Edit to update Copyright notice',
              ).save()



class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_default_system),
        migrations.RunPython(create_default_source),
        migrations.RunPython(create_default_plan),
        migrations.RunPython(create_default_agency),
        migrations.RunPython(create_default_html),
        migrations.RunPython(create_default_anonymous_user),
        migrations.RunPython(create_default_email_option),
        migrations.RunPython(create_default_copyright),
    ]
