# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-05 17:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0002_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='TranmissionUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('transmission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='radio.Transmission')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='radio.Unit')),
            ],
        ),
        migrations.AddField(
            model_name='transmission',
            name='units',
            field=models.ManyToManyField(through='radio.TranmissionUnit', to='radio.Unit'),
        ),
    ]
