# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-15 05:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0003_auto_20160605_1043'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tranmissionunit',
            options={'ordering': ['order']},
        ),
        migrations.AlterField(
            model_name='talkgroup',
            name='alpha_tag',
            field=models.CharField(max_length=30),
        ),
    ]
