# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-16 18:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0004_auto_20160614_2235'),
    ]

    operations = [
        migrations.AddField(
            model_name='talkgroup',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
