# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-10 03:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0007_scanlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='transmission',
            name='play_length',
            field=models.FloatField(default=0.0),
        ),
    ]
