# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-31 02:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0008_transmission_play_length'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='talkgroup',
            options={'ordering': ['alpha_tag']},
        ),
        migrations.AlterModelOptions(
            name='transmission',
            options={'ordering': ['-pk']},
        ),
        migrations.AddField(
            model_name='talkgroup',
            name='public',
            field=models.BooleanField(default=True),
        ),
    ]
