# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-09 21:59
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0009_auto_20160830_1951'),
    ]

    operations = [
        migrations.AddField(
            model_name='transmission',
            name='trans_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
    ]
