# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-09 22:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0010_transmission_trans_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transmission',
            old_name='trans_id',
            new_name='slug',
        ),
    ]
