# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-09 04:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0011_auto_20160909_1532'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuScanList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=1)),
            ],
            options={
                'abstract': False,
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MenuTalkGroupList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=1)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='radio.TalkGroup')),
            ],
            options={
                'abstract': False,
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AlterModelOptions(
            name='scanlist',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='menuscanlist',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='radio.ScanList'),
        ),
    ]
