# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-12 22:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0013_auto_20161012_1515'),
    ]

    operations = [
        # Setup a default source
        migrations.RunSQL([("INSERT INTO radio_source (id,description) VALUES (0,'Default');", None)]),
    ]
