# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-15 03:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0014_auto_20161012_1530'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('short', models.CharField(max_length=5)),
            ],
        ),
        migrations.AlterModelOptions(
            name='source',
            options={'ordering': ['pk']},
        ),
        migrations.AddField(
            model_name='unit',
            name='agency',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='radio.Agency'),
        ),
    ]
