# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-15 05:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0016_default_agency'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='number',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='unit',
            name='type',
            field=models.CharField(choices=[('M', 'Mobile'), ('P', 'Portable'), ('B', 'Base'), ('D', 'Dispatch')], default='M', max_length=1),
        ),
    ]
