# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-23 23:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0017_auto_20161014_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agency',
            name='short',
            field=models.CharField(max_length=5, unique=True),
        ),
    ]
