# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-02-25 16:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0021_default_plan'),
    ]

    operations = [
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('system_id', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
