# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-02-25 16:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0023_default_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='talkgroup',
            name='system',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='radio.System'),
        ),
        migrations.AddField(
            model_name='transmission',
            name='system',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='radio.System'),
        ),
        migrations.AddField(
            model_name='unit',
            name='system',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='radio.System'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='dec_id',
            field=models.IntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='talkgroup',
            unique_together=set([('dec_id', 'system')]),
        ),
        migrations.AlterUniqueTogether(
            name='unit',
            unique_together=set([('dec_id', 'system')]),
        ),
    ]
