# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-02-26 04:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0024_auto_20170225_0857'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
