# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-03-05 21:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0025_unit_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talkgroup',
            name='dec_id',
            field=models.IntegerField(),
        ),
    ]
