# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-03-07 05:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0026_auto_20170305_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='talkgroup',
            name='mode',
            field=models.CharField(choices=[('A', 'Analog'), ('D', 'Digital'), ('E', 'Encrypted')], default='D', max_length=1),
        ),
        migrations.AddField(
            model_name='talkgroup',
            name='priority',
            field=models.IntegerField(default=3),
        ),
    ]
