# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-03-08 05:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0027_auto_20170306_2118'),
    ]

    operations = [
        migrations.AddField(
            model_name='transmission',
            name='audio_file_url_path',
            field=models.CharField(default='/', max_length=100),
        ),
        migrations.AlterField(
            model_name='talkgroup',
            name='mode',
            field=models.CharField(choices=[('A', 'Analog'), ('D', 'Digital'), ('E', 'Encrypted')], default='D', help_text='mode used by trunk-recorder', max_length=1),
        ),
        migrations.AlterField(
            model_name='talkgroup',
            name='priority',
            field=models.IntegerField(default=3, help_text='record priority used by trunk-recorder'),
        ),
    ]
