# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-03-14 05:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0028_auto_20170307_2152'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanlist',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
