# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-03-19 16:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0030_scanlist_build_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebHtml',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('bodytext', models.TextField()),
            ],
        ),
    ]
