# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-05-15 03:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0032_default_webhtml'),
    ]

    operations = [
        migrations.CreateModel(
            name='TalkGroupAccess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('default_group', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TalkGroupWithSystem',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('radio.talkgroup',),
        ),
        migrations.AddField(
            model_name='talkgroupaccess',
            name='talkgroups',
            field=models.ManyToManyField(to='radio.TalkGroupWithSystem'),
        ),
        migrations.AddField(
            model_name='profile',
            name='talkgroup_access',
            field=models.ManyToManyField(to='radio.TalkGroupAccess'),
        ),
    ]
