# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-05-17 01:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
from django.contrib.auth.models import User


def create_default_anonymous_user(apps, schema_editor):
    # Moved to post migration signal
    pass


def delete_default_anonymous_user(apps, schema_editor):
    try:
        anon = User.objects.get(username='ANONYMOUS_USER')
        anon.delete()
    except User.DoesNotExist:
        pass


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0034_auto_20170516_1852'),
    ]

    operations = [
        migrations.RunPython(create_default_anonymous_user, delete_default_anonymous_user),
    ]

