# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-05-17 01:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
from django.contrib.auth.models import User


def create_default_anonymous_user(apps, schema_editor):
    anon = User.objects.create_user('ANONYMOUS_USER', 'anonymous_user@example.com')
    # Make the user un usable
    anon.set_unusable_password() 
    anon.is_active = False
    anon.save()


def delete_default_anonymous_user(apps, schema_editor):
    try:
        anon = User.objects.get(username='ANONYMOUS_USER')
        anon.delete()
    except User.DoesNotExist:
        pass


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0048_auto_20171112_1144'),
    ]

    operations = [
        migrations.RunPython(create_default_anonymous_user, delete_default_anonymous_user),
    ]

