# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-05-23 02:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0034_auto_20170516_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='talkgroup_access',
            field=models.ManyToManyField(blank=True, to='radio.TalkGroupAccess'),
        ),
    ]
