# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-27 05:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0038_stripeplanmatrix'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stripeplanmatrix',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='stripeplanmatrix',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='stripeplanmatrix',
            name='order',
            field=models.IntegerField(default=1),
        ),
    ]
