# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-27 05:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0039_auto_20170626_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stripeplanmatrix',
            name='order',
            field=models.IntegerField(default=99),
        ),
    ]
