# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-02 15:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0041_auto_20170815_2147'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='talkgroupaccess',
            options={'verbose_name_plural': 'talk group access'},
        ),
    ]
