# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-03 03:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0042_auto_20170902_0838'),
    ]

    operations = [
        migrations.AddField(
            model_name='talkgroupaccess',
            name='default_new_talkgroups',
            field=models.BooleanField(default=False, help_text='new talkgroups are added to this group'),
        ),
        migrations.AlterField(
            model_name='talkgroupaccess',
            name='default_group',
            field=models.BooleanField(default=False, help_text='new users get this group by default'),
        ),
    ]
