# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-11 04:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0043_auto_20170902_2018'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('value', models.CharField(max_length=60)),
                ('javascript_visible', models.BooleanField(default=False)),
                ('template_visible', models.BooleanField(default=False)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
