# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-12 19:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0046_transmission_audio_file_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transmission',
            name='audio_file_type',
            field=models.CharField(default='mp3', max_length=3, null=True),
        ),
    ]
