# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-08 06:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0048_auto_20171112_1144'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('public', models.BooleanField(default=True)),
                ('transmissions', models.ManyToManyField(blank=True, to='radio.Transmission')),
            ],
        ),
    ]
