# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-27 04:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0049_incident'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('url', models.URLField(blank=True, max_length=400, null=True)),
                ('google_maps_url', models.URLField(blank=True, max_length=400, null=True)),
            ],
        ),
    ]
