# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-08 01:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0050_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='ems_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ems_service', to='radio.Agency'),
        ),
        migrations.AddField(
            model_name='city',
            name='fire_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fire_service', to='radio.Agency'),
        ),
        migrations.AddField(
            model_name='city',
            name='police_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='police_service', to='radio.Agency'),
        ),
    ]
