# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-08 02:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0051_auto_20180107_1729'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='city',
            name='visable',
            field=models.BooleanField(default=True),
        ),
    ]
