# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-08 03:47
from __future__ import unicode_literals

from django.db import migrations, models
from django.db.migrations.operations.fields import RemoveField


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0052_auto_20180107_1846'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='visable',
            new_name='visible',
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
