# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-12 05:35
from __future__ import unicode_literals

from django.utils import timezone
import pytz
from django.db import migrations, models
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0053_auto_20180107_1947'),
    ]
    tz = pytz.timezone(settings.TIME_ZONE)
    operations = [
        migrations.AddField(
            model_name='talkgroup',
            name='last_transmission',
            field=models.DateTimeField(default=timezone.datetime(2010, 1, 1, 0, 0, tzinfo=tz)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='talkgroup',
            name='recent_usage',
            field=models.IntegerField(default=0),
        ),
    ]
