# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-20 01:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0054_auto_20180111_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='transmission',
            name='end_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
