# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-20 05:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0055_transmission_end_datetime'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessagePopUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mesg_type', models.CharField(choices=[('A', 'All Pages'), ('H', 'Home Page')], max_length=1, unique=True)),
                ('mesg_html', models.TextField()),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
