# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-01-02 21:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0056_messagepopup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='system',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
