# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-01-02 22:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0058_auto_20190102_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='description',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
    ]
