# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-04 04:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0059_auto_20190102_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='talkgroup',
            name='play_source',
            field=models.ForeignKey(blank=True, help_text='default record source for playback', null=True, on_delete=django.db.models.deletion.CASCADE, to='radio.Source'),
        ),
        migrations.AddField(
            model_name='transmission',
            name='from_default_source',
            field=models.BooleanField(default=True),
        ),
    ]
