# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-04 22:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0060_auto_20190103_2002'),
    ]

    operations = [
        migrations.AddField(
            model_name='transmission',
            name='has_audio',
            field=models.BooleanField(default=True),
        ),
    ]
