# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-18 17:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0062_auto_20190118_0918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recorderpc',
            name='hostname',
            field=models.CharField(db_index=True, max_length=20, unique=True),
        ),
    ]
