# Generated by updating slug fields for uniqueness across systems

from django.db import migrations, models
from django.utils.text import slugify


def update_talkgroup_slugs(apps, schema_editor):
    """Update existing TalkGroup slugs to include system prefix"""
    TalkGroup = apps.get_model('radio', 'TalkGroup')

    for tg in TalkGroup.objects.all():
        base_slug = slugify(tg.alpha_tag)
        new_slug = f"sys{tg.system_id}-{base_slug}"
        tg.slug = new_slug
        tg.save()


def update_user_scan_list_slugs(apps, schema_editor):
    """Generate slugs for existing UserScanList records"""
    UserScanList = apps.get_model('radio', 'UserScanList')

    for scan_list in UserScanList.objects.all():
        base_slug = slugify(scan_list.name)
        new_slug = f"user{scan_list.user_id}-{base_slug}"
        scan_list.slug = new_slug
        scan_list.save()


def reverse_talkgroup_slugs(apps, schema_editor):
    """Reverse TalkGroup slug changes"""
    TalkGroup = apps.get_model('radio', 'TalkGroup')

    for tg in TalkGroup.objects.all():
        base_slug = slugify(tg.alpha_tag)
        tg.slug = base_slug
        tg.save()


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0063_add_fine_grained_auth'),
    ]

    operations = [
        # Add slug field to UserScanList (non-unique first)
        migrations.AddField(
            model_name='userscanlist',
            name='slug',
            field=models.SlugField(null=True),
        ),

        # Generate initial slugs for UserScanList
        migrations.RunPython(update_user_scan_list_slugs, migrations.RunPython.noop),

        # Update existing TalkGroup slugs with system prefix
        migrations.RunPython(update_talkgroup_slugs, reverse_talkgroup_slugs),
    ]