# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-18 18:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0063_auto_20190118_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transmission',
            name='recorder_pc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='radio.RecorderPC'),
        ),
    ]
