# Generated by making slug fields unique after data population

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0064_update_slugs_for_uniqueness'),
    ]

    operations = [
        # Make UserScanList slug unique
        migrations.AlterField(
            model_name='userscanlist',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),

        # Make TalkGroup slug unique
        migrations.AlterField(
            model_name='talkgroup',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]